# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBlu-5Urpvqks3H5H3rvQZTtjfKprsfP
"""

import gradio as gr


def bubble_sort(numbers, ascending=True):
    """
    Bubble sort implementation that records step-by-step actions.
    :param numbers: list of integers
    :param ascending: True for ascending, False for descending
    :return: (sorted_list, steps_text)
    """
    steps = []
    arr = list(numbers)  # copy so we don't mutate original input
    n = len(arr)

    if n == 0:
        return arr, "List is empty. Nothing to sort."

    steps.append(f"Initial list: {arr}")

    # Outer loop for passes
    for i in range(n):
        swapped = False
        steps.append(f"\nPass {i + 1} starting: {arr}")

        # Inner loop compares adjacent pairs
        for j in range(0, n - i - 1):
            compare_info = (
                f"Compare arr[{j}] = {arr[j]} and arr[{j + 1}] = {arr[j + 1]}"
            )

            should_swap = (
                (ascending and arr[j] > arr[j + 1])
                or (not ascending and arr[j] < arr[j + 1])
            )

            if should_swap:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
                steps.append(compare_info + f" --> swap → {arr}")
            else:
                steps.append(compare_info + " --> no change")

        if not swapped:
            steps.append("No swaps in this pass → list is already sorted. Stop early.")
            break

    steps.append(f"\nFinal sorted list: {arr}")
    return arr, "\n".join(steps)


def parse_input_list(input_text):
    """
    Convert comma-separated string to list of integers.
    Handles spaces and basic validation errors.
    """
    if not input_text.strip():
        raise ValueError("Input is empty. Please enter at least one number.")

    parts = input_text.split(",")
    numbers = []
    for p in parts:
        p = p.strip()
        if p == "":
            continue
        try:
            num = int(p)
        except ValueError:
            raise ValueError(
                f"'{p}' is not a valid integer. "
                "Please enter only whole numbers separated by commas."
            )
        numbers.append(num)

    if len(numbers) == 0:
        raise ValueError("No valid numbers found. Please enter at least one integer.")

    return numbers


def bubble_sort_ui(input_list, order, show_steps):
    """
    Wrapper function for Gradio UI.

    :param input_list: string from the textbox
    :param order: "Ascending" or "Descending"
    :param show_steps: bool
    :return: (sorted_list_str, steps_text)
    """
    try:
        numbers = parse_input_list(input_list)
    except ValueError as e:
        # Return error message in steps box, and empty sorted result
        return "", f"⚠️ Input Error: {e}\n\nExample: 5, 1, 4, 2, 8"

    ascending = (order == "Ascending")
    sorted_list, steps_text = bubble_sort(numbers, ascending=ascending)

    sorted_list_str = ", ".join(str(x) for x in sorted_list)

    if not show_steps:
        # Short explanation only
        short_explanation = (
            "Bubble Sort repeatedly compares adjacent elements and swaps them\n"
            "if they are in the wrong order. After each pass, the largest (or smallest)\n"
            "value 'bubbles up' to its correct position.\n\n"
            f"Input: {numbers}\nSorted: {sorted_list}"
        )
        return sorted_list_str, short_explanation

    return sorted_list_str, steps_text


with gr.Blocks() as demo:
    gr.Markdown(
        """
    # 🫧 Bubble Sort Visualizer (CISC-121)

    This app lets you **learn Bubble Sort** step-by-step.

    - Enter a list of integers (comma-separated)
    - Choose ascending or descending order
    - See how Bubble Sort compares and swaps values on each pass
    """
    )

    with gr.Row():
        input_list = gr.Textbox(
            label="Enter a list of integers (comma-separated)",
            value="5, 1, 4, 2, 8",
            placeholder="e.g., 5, 1, 4, 2, 8",
        )

    with gr.Row():
        order = gr.Radio(
            ["Ascending", "Descending"],
            value="Ascending",
            label="Sort Order",
        )
        show_steps = gr.Checkbox(
            value=True,
            label="Show step-by-step explanation",
        )

    run_button = gr.Button("Run Bubble Sort")

    sorted_output = gr.Textbox(
        label="✅ Sorted List",
        interactive=False,
    )
    steps_output = gr.Textbox(
        label="🧠 Algorithm Steps / Explanation",
        lines=18,
        interactive=False,
    )

    run_button.click(
        fn=bubble_sort_ui,
        inputs=[input_list, order, show_steps],
        outputs=[sorted_output, steps_output],
    )


# For local testing: `python app.py`
if __name__ == "__main__":
    demo.launch()