# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imXZsr-iqXZhPdrgvUB1UCq9TAsW0Rg_
"""

# Bubble Sort Visualizer (CISC-121 Project)

## Demo Screenshot / GIF

> _Add a screenshot or GIF of your Hugging Face app here._
> Example: `![Bubble Sort Demo](screenshot.png)`

---

## Problem Breakdown & Computational Thinking

### 1. Decomposition

I broke the problem into smaller parts:

- **Input handling**:
  - Read a comma-separated string from the user.
  - Validate that each value is an integer.
- **Algorithm logic (Bubble Sort)**:
  - Implement the core Bubble Sort loop with passes and swaps.
- **Step recording**:
  - For each comparison and swap, record a text description.
- **User interface (Gradio)**:
  - Textbox for list input.
  - Radio button for ascending vs descending.
  - Checkbox for “show step-by-step”.
  - Output boxes for the final sorted list and explanation.
- **Error handling**:
  - Show clear messages if the input is empty or invalid.

### 2. Pattern Recognition

- Bubble Sort always:
  - Compares **adjacent** elements: `arr[j]` and `arr[j+1]`.
  - Repeats passes over the list.
  - After each pass, one element is in its correct position at the end.
- This repeating pattern of:
  - *Compare → maybe swap → move to next pair*
  is used in the code as nested loops.

### 3. Abstraction

To make the app easier to use:

- The user only sees:
  - A simple textbox (numbers separated by commas),
  - The chosen sort order,
  - A friendly explanation of what happens.
- The internal steps like indices, loops, and boolean flags are **hidden**.
- The UI abstracts away:
  - Python data structures,
  - Implementation details,
  - Technical error messages.

### 4. Algorithm Design (Input → Processing → Output)

- **Input:**
  - A string such as: `"5, 1, 4, 2, 8"`.
  - Option for `Ascending` or `Descending`.
  - Checkbox: show full steps or just a summary.

- **Processing:**
  1. Parse the string into a list of integers.
  2. Run Bubble Sort:
     - For each pass:
       - Compare adjacent elements.
       - Swap if out of order.
       - Record each comparison and swap as text.
     - Stop early if no swaps in a pass.

- **Output:**
  - Final sorted list as a neat string, e.g. `"1, 2, 4, 5, 8"`.
  - A detailed explanation of what happened in each pass (if enabled), or a short summary.

---

## Steps to Run (Locally)

1. **Clone or download** this repository.

2. Create and activate a virtual environment (optional but recommended):

   ```bash
   python -m venv venv
   source venv/bin/activate   # on macOS / Linux
   venv\Scripts\activate      # on Windows