# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imXZsr-iqXZhPdrgvUB1UCq9TAsW0Rg_
"""

gradio>=4.0.0